skills = {
#covert
            'co.st': 'DDDIS',
            'co.hi': 'DDIIS',
            'co.lo': 'DDDDI',
            'co.ma': 'DDISS',
            'co.ca': 'DIIWW',
            'co.it': 'DIIII',
            'co.po': 'DDIIC',
# faith   
            'fa.ri.of': 'ISSWW',
            'fa.ri.de': 'DDIWW',
            'fa.ri.cu': 'CCIWW',
            'fa.ri.mi': 'IIWWW',
            'fa.ri.sp': 'ISWWW',
            'fa.it':     'DIIWW',
            'fa.po':    'CIIWW',
# magic            
            'ma.sp.of': 'SSIIW',
            'ma.sp.de': 'CCIIW',
            'ma.sp.mi': 'DDIIW',
            'ma.sp.sp': 'IIWWW',
            'ma.me.el': 'CCCII',
            'ma.me.me': 'IIIII',
            'ma.me.ph': 'DDDII',
            'ma.me.sp': 'IIWWW',
            'ma.it':    'DIIWW',
            'ma.po':    'IISWW',
# fighting            
            'fi.me.da': 'DDDDS',
            'fi.me.sw': 'DDDSS',
            'fi.me.po': 'CCSSS',
            'fi.me.he': 'CDSSS',
            'fi.me.ma': 'CCDSS',
            'fi.ra.th': 'DDDSS',
            'fi.ra.fi': 'DDDDS',
            'fi.de.do': 'DDDDW',
            'fi.de.pa': 'DDDSW',
            'fi.de.bl': 'DDSSW',
            'fi.sp.we': 'SDIII',
            'fi.sp.ta': 'WWIII',
            'fi.po':    'DSSCC',
# adventuring: perception, health
            'ad.pe':    'IIWWW',
            'ad.he':    'CCCCS',
            
            'utility':     'SSCCC',
            'test':     'SSSSS',
}
